source:
  type: csv
  path: /home/han/data-generator/test_data
  pattern: "*.csv"

sink:
  type: kafka
  bootstrap_servers: localhost:19092,localhost:29092,localhost:39092
  topic: sensor-data

settings:
  messages_per_second: 1
  batch_size: 2
  run_time: 30  # 30 saniye çalış
  log_level: INFO
