source:
  type: csv
  path: /home/han/data-generator/test_data
  pattern: "*.csv"

sink:
  type: kafka
  bootstrap_servers: localhost:9092  # Mevcut Kafka kurulumunuzun adresi
  topic: test-data-stream

settings:
  messages_per_second: 1
  batch_size: 2
  run_time: 30  # 30 saniye çalış
  log_level: INFO
